from datetime import datetime
from typing import Optional
from sqlalchemy import String, Text, Float, Integer
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base, TimestampMixin


class AIInsight(Base, TimestampMixin):
    """Structured ecological insights generated by the BioIntel AI engine."""
    __tablename__ = "ai_insights"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True, index=True)
    type: Mapped[str] = mapped_column(String(100), nullable=False, default="ECOLOGICAL_TREND")
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    evidence: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    confidence: Mapped[str] = mapped_column(String(50), default="Moderate", nullable=False)  # High, Moderate, Low
    recommendations: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<AIInsight id={self.id} title='{self.title}' confidence='{self.confidence}'>"
